apiVersion: v1
kind: Pod
metadata:
  name: http-server-graceful
spec:
    containers:
    - name: http-server-graceful
      image: http-server-graceful
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 2
      readinessProbe:
        httpGet:
          path: /readiness
          port: 8080
        initialDelaySeconds: 2
        periodSeconds: 1
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo 'The http server is running!'"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "pkill -f http-server-graceful"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "500m"
    volumes:
        - name: config-volume
          configMap:
            name: example-configmap
    volumeMounts:
        - name: config-volume
          mountPath: /etc/config
          readOnly: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
data:
  config.json: |
    {
      "name": "chris"
    }


